version: '3.8'

services:
  nginx:
    image: my_nginx
    build: ./requirements/nginx
    container_name: nginx
    networks:
      - inception-network
    restart: on-failure
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html/wordpress

  wordpress:
    image: my_wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    networks:
      - inception-network
    restart: on-failure
    depends_on:
      - mariadb
      - redis
    volumes:
      - wordpress:/var/www/html/wordpress
    environment:
      DB_WP_NAME: ${DB_WP_NAME}
      DB_WP_USER_NAME: ${DB_WP_USER_NAME}
      DB_WP_USER_PASS: ${DB_WP_USER_PASS}
      DB_HOST: ${DB_HOST}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASS: ${WP_ADMIN_PASS}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}

  mariadb:
    image: my_mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    networks:
      - inception-network
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      DB_WP_NAME: ${DB_WP_NAME}
      DB_WP_USER_NAME: ${DB_WP_USER_NAME}
      DB_WP_USER_PASS: ${DB_WP_USER_PASS}
      DB_ROOT_USER_PASS: ${DB_ROOT_USER_PASS}

  redis:
    image: my_redis
    build: ./requirements/bonus/redis
    container_name: redis
    networks:
      - inception-network
    restart: on-failure

  adminer:
    image: my_adminer
    build: ./requirements/bonus/adminer
    container_name: adminer
    networks:
      - inception-network
    restart: on-failure

  ftp:
    image: my_ftp
    build: ./requirements/bonus/ftp
    container_name: ftp
    restart: on-failure
    ports:
      - "21:21"
      - "50001:50001"
    volumes:
      - wordpress:/var/www/html/wordpress
    environment:
      FTP_TEST_USER_PASS: ${FTP_TEST_USER_PASS}

networks:
  inception-network:
    name: inception-network

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      o: bind
      type: none
      device: /home/mkamei/data/wordpress
  mariadb:
    name: mariadb
    driver_opts:
      o: bind
      type: none
      device: /home/mkamei/data/mariadb
