version: '3.8'

services:
  nginx:
    image: nginx:inception
    build: ./requirements/nginx
    container_name: nginx
    init: true
    networks:
      - inception-network
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html/wordpress
      - adminer:/var/www/html/adminer

  wordpress:
    image: wordpress:inception
    build: ./requirements/wordpress
    container_name: wordpress
    init: true
    networks:
      - inception-network
    restart: always
    depends_on:
      - mariadb
      - redis
    volumes:
      - wordpress:/var/www/html/wordpress
    environment:
      DB_WP_NAME: ${DB_WP_NAME}
      DB_WP_USER_NAME: ${DB_WP_USER_NAME}
      DB_WP_USER_PASS: ${DB_WP_USER_PASS}
      DB_HOST: ${DB_HOST}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASS: ${WP_ADMIN_PASS}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_AUTHOR_USER: ${WP_AUTHOR_USER}
      WP_AUTHOR_PASS: ${WP_AUTHOR_PASS}
      WP_AUTHOR_EMAIL: ${WP_AUTHOR_EMAIL}

  mariadb:
    image: mariadb:inception
    build: ./requirements/mariadb
    container_name: mariadb
    init: true
    networks:
      - inception-network
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      DB_WP_NAME: ${DB_WP_NAME}
      DB_WP_USER_NAME: ${DB_WP_USER_NAME}
      DB_WP_USER_PASS: ${DB_WP_USER_PASS}
      DB_ROOT_USER_PASS: ${DB_ROOT_USER_PASS}

  redis:
    image: redis:inception
    build: ./requirements/bonus/redis
    container_name: redis
    init: true
    networks:
      - inception-network
    restart: always

  adminer:
    image: adminer:inception
    build: ./requirements/bonus/adminer
    container_name: adminer
    init: true
    networks:
      - inception-network
    restart: always
    volumes:
      - adminer:/var/www/html/adminer

  ftp:
    image: ftp:inception
    build: ./requirements/bonus/ftp
    container_name: ftp
    init: true
    restart: always
    ports:
      - "21:21"
      - "50001:50001"
    volumes:
      - wordpress:/var/www/html/wordpress
    environment:
      FTP_TEST_USER_PASS: ${FTP_TEST_USER_PASS}

networks:
  inception-network:
    name: inception-network

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/mkamei/data/wordpress
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/mkamei/data/mariadb
  adminer:
    name: adminer
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/mkamei/data/adminer
