version: '3.8'

services:
  nginx:
    image: my_nginx
    build: ./requirements/nginx
    container_name: nginx
    networks:
      - inception-network
    restart: on-failure
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html/wordpress

  wordpress:
    image: my_wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    networks:
      - inception-network
    restart: on-failure
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html/wordpress

  mariadb:
    image: my_mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    networks:
      - inception-network
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql

networks:
  inception-network:
    name: inception-network

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      o: bind
      type: none
      device: /home/mkamei/data/wordpress
  mariadb:
    name: mariadb
    driver_opts:
      o: bind
      type: none
      device: /home/mkamei/data/mariadb
